title: PACE Academy Self Help Centre
remote_theme: opendocsg/opendoc-theme@v2
repository: opendocsg/opendoc-supreme-court-judgments
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: 'https://search.opendoc.sg'
server_DEV: 'https://search-staging.opendoc.sg'
fast_build: true
offline_search_only: false
styling_options:
  primary_brand_color: '#000080'
  logo_path: /assets/sp3.jpg
  opendoc_logo_path: /assets/sp3.jpg
document_order:
  - QuickArticles
  - Technical
