title: PACE Academy Self Help Centre
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sp-self-help-centre
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: 'https://search.opendoc.sg'
server_DEV: 'https://search-staging.opendoc.sg'
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

offline_search_only: false
styling_options:
  primary_brand_color: '#000080'
  logo_path: /assets/sp3.jpg
  opendoc_logo_path: /assets/sp3.jpg
document_order:
  - QuickArticles
  - Technical
